# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:

  # Backend (points to pyproject.toml in root directory)
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    assignees:
      - 'dreulavelle'
