stages:
  - build_container
  - build_slim

build_container:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always  # Run only on push events
    - when: never # never otherswise
  image: docker:26.1.1
  
  stage: build_container
  tags:
    - Build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "The current project id number is $CI_PROJECT_ID"
    - docker build --output type=docker -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker build --output type=docker -t $CI_REGISTRY_IMAGE:latest-dbg -f Dockerfile.debug .
    - docker push $CI_REGISTRY_IMAGE:latest-dbg
 
build_slim:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases
  image: docker:26.1.1
  
  stage: build_container
  tags:
    - Build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "The current project id number is $CI_PROJECT_ID"
    - docker build --output type=docker -t $CI_REGISTRY_IMAGE:slim -f Dockerfile.slim .
    - docker push $CI_REGISTRY_IMAGE:slim
